# .air.toml
[build]
cmd = "go build -o main.exe main.go"
bin = "./main.exe"
full_bin = "./main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
level = "debug"
